server:
  port: 8068

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html



