spring:
  application:
    name: transaction-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8060}
  datasource:
    url: ${TRANSACTION_DB_URL:jdbc:postgresql://localhost:5432/transaction_db}
    username: ${TRANSACTION_DB_USERNAME:postgres}
    password: ${TRANSACTION_DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2s

  cache:
    type: redis

server:
  port: 8068

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8061/eureka/}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


