server:
  port: 8060

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI:file:../}
          default-label: main
          clone-on-start: true
          search-paths: github-config
          username: ${GIT_USERNAME:}
          password: ${GIT_PAT:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,env
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true



